services:
  - type: web
    name: gjeniu-i-vogel-frontend
    env: static
    buildCommand: echo "No build needed for static site"
    startCommand: echo "Static site ready"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 