services:
  - type: web
    name: gjeniu-i-vogel-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"
    healthCheck:
      path: /api/health
      initialDelaySeconds: 15
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://gjeniu_user:Erisa.12@cluster0.lealz2d.mongodb.net/gjeniu-i-vogel?retryWrites=true&w=majority&appName=Cluster0
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: loritahasani5@gmail.com
      - key: MAIL_PASSWORD
        value: wmva xbck ibda amra
        # TODO: Replace with your Gmail app password
      - key: MAIL_DEFAULT_SENDER
        value: loritahasani5@gmail.com 